### ISSUE TITLE
Various issues with optimizers

### ISSUE THREAD

**Issue by mkounkel** [phoebe-project/phoebe2-ui#6] opened 2021-02-06 21:05 UTC
Running various optimizers on the online interface - seems like they are all broken to various degree. Not sure if I'm doing something wrong.

**Ebai** (actually on the online interface) Failed with error: UnboundLocalError: local variable 't0_supconj_param' referenced before assignment
Exported to run locally - runs, but, doesn't seem to do anything? I was hoping that it'd at least fix t0 - lc_geometry one works, but it's a tricky system, so it gets confused.

**RV_geometry**, on the other hand, doesn't work, exits with the message of "Failed with error: IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 7" -> I have a feeling that it's due to the fact that there are 7 epochs for the primary, and only 5 for the secondary?

**nelder_mead** the only one that seems to run, after exporting. But, it goes well past maxiter, so it hards to figure when it's actually going to stop. It can finish, I ran it overnight, and it has seemed to work.

**CG** aborts after 5 minutes with no follow-up beyond this, though, it does produce a rather useless .out file.

/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:156: RuntimeWarning: invalid value encountered in double_scalars
  alpha1 = min(1.0, 1.01*2*(phi0 - old_phi0)/derphi0)
/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:392: RuntimeWarning: invalid value encountered in double_scalars
  alpha1 = min(1.0, 1.01*2*(phi0 - old_phi0)/derphi0)
  0%|                                                                                                                                                                                                      | 0/1000 [05:00<?, ?it/s]

**powell** - ran it overnight on a different machine, seems to unceremoniously quit after 10 epochs? The only thing it has is this message
/Users/kounkem/opt/anaconda3/lib/python3.7/site-packages/scipy/optimize/optimize.py:2149: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
  1%|█▎                                                                                                                                       | 10/1000 [6:35:53<653:13:19, 2375.35s/it]
Does produce an out file, with some estimates, but, trying to import it back in and generate a model from it gives "Failed with error: TypeError: only size-1 arrays can be converted to Python scalars" - it may be related to t0_supconj - I had hard time adjusting it by hand, too, it gave that error on an occasion if I changed it, let's say from 2.9 to 3.0...

**differential_evolution** gives this error from the get go.

 File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 727, in to_value
    scale = self.unit._to(unit)
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 951, in _to
    f"'{self!r}' is not a scaled version of '{other!r}'")
astropy.units.core.UnitConversionError: 'Unit("d")' is not a scaled version of 'Unit(dimensionless)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 1073, in __float__
    return float(self.to_value(dimensionless_unscaled))
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 730, in to_value
    value = self._to_value(unit, equivalencies)
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 661, in _to_value
    equivalencies=equivalencies)
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 987, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 918, in _get_converter
    raise exc
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 904, in _get_converter
    self, other, self._normalize_equivalencies(equivalencies))
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 888, in _apply_equivalencies
    unit_str, other_str))
astropy.units.core.UnitConversionError: 'd' (time) and '' (dimensionless) are not convertible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "oynIHF_run_solver_differential_evolution01.py", line 6, in <module>
    solution_ps = b.run_solver(out_fname=sys.argv[0]+'.out', solver='differential_evolution01',solution='latest')
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/phoebe/parameters/parameters.py", line 401, in _send_if_client
    return fctn(self, *args, **kwargs)
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/phoebe/frontend/bundle.py", line 11539, in run_solver
    params = solver_class().run(self, solver_ps.solver, compute, solution=solution, **{k:v for k,v in kwargs.items() if k not in ['compute']})
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/phoebe/solverbackends/solverbackends.py", line 511, in run
    rpacketlists_per_worker = [self.run_worker(**packet)]
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/phoebe/solverbackends/solverbackends.py", line 1970, in run_worker
    **options)
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/scipy/optimize/_differentialevolution.py", line 305, in differential_evolution
    constraints=constraints) as solver:
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/scipy/optimize/_differentialevolution.py", line 534, in __init__
    self.limits = np.array(bounds, dtype='float').T
  File "/Users/mkounkel/opt/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 1075, in __float__
    raise TypeError('only dimensionless scalar quantities can be '
TypeError: only dimensionless scalar quantities can be converted to Python scalars

(pretty sure the error here is for the period, when I also included reqiv, it complained about Rsun first)

Haven't tried the samplers yet.

**Comment by kecnry** [comment] 2021-02-06 22:55
The issues you ran into with ebai were fixed in PHOEBE 2.3.18 and the one for rv_geometry in 2.3.16, but the server is only running 2.3.0, which is why they are working on your machine but not when running directly through the web UI.  I will update the version running on the website as soon as I see that no one is actively using it for a while (to try to prevent killing anyone's session  **EDIT:** server has been updated to 2.3.19).  However, ebai will now just return nans for you instead of throwing that ugly error - it is not currently trained to handle systems with wide eclipses.

Nelder-mead can go over the prescribed maxiter and maxfev - I don't think there is anything that can be done about that as we just pass the information on to scipy's optimizer package.  I agree, that it can be quite frustrating, especially since there is no useful output if you have to kill it before it completes.  However, I've found that if you start with only one or a few parameters that are most sensitive to the residuals and slowly introduce more parameters, it is actually quite efficient.  You can also set xatol and fatol to try to keep each run short - and can always adopt the solution from one run and continue another where it left off if it still isn't sufficiently converged.

As for the others, there does seem to be something odd going on in those cases, that may be a bug in phoebe.  If you can attach the scripts from export_solver, I can try to reproduce and debug the issues (if there is any sensitive data that you don't want public here, feel free to email them to me instead or create a case with fake data that shows the same problem).

Thanks!

**Closed as completed** 2021-07-09 13:36 UTC
